
function generateSlug(title) {
    return title
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-') // Replace non-alphanumeric characters with '-'
        .replace(/^-+|-+$/g, '');    // Remove leading or trailing '-'
}

export const array = [
    { title: 'Example title 1', duration: '1 min', tag: 'Content', slug: generateSlug('Example title 1') },
    { title: 'Example title 2', duration: '3 mins', tag: 'SEO', slug: generateSlug('Example title 2') },
    { title: 'Example title 3', duration: '5 mins', tag: 'Sales', slug: generateSlug('Example title 3') },
    { title: 'Example title 4', duration: '2 mins', tag: 'Social', slug: generateSlug('Example title 4') },
    { title: 'Example title 5', duration: '4 mins', tag: 'Ads', slug: generateSlug('Example title 5') },
    { title: 'Example title 6', duration: '3 mins', tag: 'Copywriting', slug: generateSlug('Example title 6') },
    { title: 'Example title 7', duration: '1 min', tag: 'Landing Page', slug: generateSlug('Example title 7') },
    { title: 'Example title 8', duration: '4 mins', tag: 'Retention', slug: generateSlug('Example title 8') },
    { title: 'Example title 9', duration: '2 mins', tag: 'Brand', slug: generateSlug('Example title 9') },
    { title: 'Example title 10', duration: '5 mins', tag: 'Referral', slug: generateSlug('Example title 10') },
    { title: 'Example title 11', duration: '2 mins', tag: 'Creative', slug: generateSlug('Example title 11') },
    { title: 'Example title 12', duration: '3 mins', tag: 'Content', slug: generateSlug('Example title 12') },
    { title: 'Example title 13', duration: '5 mins', tag: 'SEO', slug: generateSlug('Example title 13') },
    { title: 'Example title 14', duration: '1 min', tag: 'Sales', slug: generateSlug('Example title 14') },
    { title: 'Example title 15', duration: '4 mins', tag: 'Social', slug: generateSlug('Example title 15') },
    { title: 'Example title 16', duration: '2 mins', tag: 'Ads', slug: generateSlug('Example title 16') },
    { title: 'Example title 17', duration: '3 mins', tag: 'Copywriting', slug: generateSlug('Example title 17') },
    { title: 'Example title 18', duration: '5 mins', tag: 'Landing Page', slug: generateSlug('Example title 18') },
    { title: 'Example title 19', duration: '4 mins', tag: 'Retention', slug: generateSlug('Example title 19') },
    { title: 'Example title 20', duration: '1 min', tag: 'Brand', slug: generateSlug('Example title 20') },
    { title: 'Example title 21', duration: '3 mins', tag: 'Referral', slug: generateSlug('Example title 21') },
    { title: 'Example title 22', duration: '2 mins', tag: 'Creative', slug: generateSlug('Example title 22') },
    { title: 'Example title 23', duration: '5 mins', tag: 'Content', slug: generateSlug('Example title 23') },
    { title: 'Example title 24', duration: '4 mins', tag: 'SEO', slug: generateSlug('Example title 24') },
    { title: 'Example title 25', duration: '1 min', tag: 'Sales', slug: generateSlug('Example title 25') },
    { title: 'Example title 26', duration: '3 mins', tag: 'Social', slug: generateSlug('Example title 26') },
    { title: 'Example title 27', duration: '2 mins', tag: 'Ads', slug: generateSlug('Example title 27') },
    { title: 'Example title 28', duration: '5 mins', tag: 'Copywriting', slug: generateSlug('Example title 28') },
    { title: 'Example title 29', duration: '4 mins', tag: 'Landing Page', slug: generateSlug('Example title 29') },
    { title: 'Example title 30', duration: '1 min', tag: 'Retention', slug: generateSlug('Example title 30') },
    { title: 'Example title 31', duration: '2 mins', tag: 'Brand', slug: generateSlug('Example title 31') },
    { title: 'Example title 32', duration: '3 mins', tag: 'Referral', slug: generateSlug('Example title 32') },
    { title: 'Example title 33', duration: '5 mins', tag: 'Creative', slug: generateSlug('Example title 33') },
    { title: 'Example title 34', duration: '4 mins', tag: 'Content', slug: generateSlug('Example title 34') },
    { title: 'Example title 35', duration: '1 min', tag: 'SEO', slug: generateSlug('Example title 35') },
    { title: 'Example title 36', duration: '3 mins', tag: 'Sales', slug: generateSlug('Example title 36') },
    { title: 'Example title 37', duration: '2 mins', tag: 'Social', slug: generateSlug('Example title 37') },
    { title: 'Example title 38', duration: '5 mins', tag: 'Ads', slug: generateSlug('Example title 38') },
    { title: 'Example title 39', duration: '4 mins', tag: 'Copywriting', slug: generateSlug('Example title 39') },
    { title: 'Example title 40', duration: '1 min', tag: 'Landing Page', slug: generateSlug('Example title 40') },
    { title: 'Example title 41', duration: '2 mins', tag: 'Retention', slug: generateSlug('Example title 41') },
    { title: 'Example title 42', duration: '3 mins', tag: 'Brand', slug: generateSlug('Example title 42') },
    { title: 'Example title 43', duration: '5 mins', tag: 'Referral', slug: generateSlug('Example title 43') },
    { title: 'Example title 44', duration: '4 mins', tag: 'Creative', slug: generateSlug('Example title 44') },
    { title: 'Example title 45', duration: '1 min', tag: 'Content', slug: generateSlug('Example title 45') },
    { title: 'Example title 46', duration: '3 mins', tag: 'SEO', slug: generateSlug('Example title 46') },
    { title: 'Example title 47', duration: '2 mins', tag: 'Sales', slug: generateSlug('Example title 47') },
    { title: 'Example title 48', duration: '5 mins', tag: 'Social', slug: generateSlug('Example title 48') },
    { title: 'Example title 49', duration: '4 mins', tag: 'Ads', slug: generateSlug('Example title 49') },
    { title: 'Example title 50', duration: '1 min', tag: 'Copywriting', slug: generateSlug('Example title 50') },
    { title: 'Example title 51', duration: '2 mins', tag: 'Landing Page', slug: generateSlug('Example title 51') },
    { title: 'Example title 52', duration: '3 mins', tag: 'Retention', slug: generateSlug('Example title 52') },
    { title: 'Example title 53', duration: '5 mins', tag: 'Brand', slug: generateSlug('Example title 53') },
    { title: 'Example title 54', duration: '4 mins', tag: 'Referral', slug: generateSlug('Example title 54') },
    { title: 'Example title 55', duration: '1 min', tag: 'Creative', slug: generateSlug('Example title 55') },
    { title: 'Example title 56', duration: '3 mins', tag: 'Content', slug: generateSlug('Example title 56') },
    { title: 'Example title 57', duration: '2 mins', tag: 'SEO', slug: generateSlug('Example title 57') },
    { title: 'Example title 58', duration: '5 mins', tag: 'Sales', slug: generateSlug('Example title 58') },
    { title: 'Example title 59', duration: '4 mins', tag: 'Social', slug: generateSlug('Example title 59') },
    { title: 'Example title 60', duration: '1 min', tag: 'Ads', slug: generateSlug('Example title 60') },
    { title: 'Example title 61', duration: '3 mins', tag: 'Copywriting', slug: generateSlug('Example title 61') },
    { title: 'Example title 62', duration: '2 mins', tag: 'Landing Page', slug: generateSlug('Example title 62') },
    { title: 'Example title 63', duration: '5 mins', tag: 'Retention', slug: generateSlug('Example title 63') },
    { title: 'Example title 64', duration: '4 mins', tag: 'Brand', slug: generateSlug('Example title 64') },
    { title: 'Example title 65', duration: '1 min', tag: 'Referral', slug: generateSlug('Example title 65') },
    { title: 'Example title 66', duration: '3 mins', tag: 'Creative', slug: generateSlug('Example title 66') },
    { title: 'Example title 67', duration: '2 mins', tag: 'Content', slug: generateSlug('Example title 67') },
    { title: 'Example title 68', duration: '5 mins', tag: 'SEO', slug: generateSlug('Example title 68') },
    { title: 'Example title 69', duration: '4 mins', tag: 'Sales', slug: generateSlug('Example title 69') },
    { title: 'Example title 70', duration: '1 min', tag: 'Social', slug: generateSlug('Example title 70') },
    { title: 'Example title 71', duration: '3 mins', tag: 'Ads', slug: generateSlug('Example title 71') },
    { title: 'Example title 72', duration: '2 mins', tag: 'Copywriting', slug: generateSlug('Example title 72') },
    { title: 'Example title 73', duration: '5 mins', tag: 'Landing Page', slug: generateSlug('Example title 73') },
    { title: 'Example title 74', duration: '4 mins', tag: 'Retention', slug: generateSlug('Example title 74') },
    { title: 'Example title 75', duration: '1 min', tag: 'Brand', slug: generateSlug('Example title 75') },
    { title: 'Example title 76', duration: '3 mins', tag: 'Referral', slug: generateSlug('Example title 76') },
    { title: 'Example title 77', duration: '2 mins', tag: 'Creative', slug: generateSlug('Example title 77') },
    { title: 'Example title 78', duration: '5 mins', tag: 'Content', slug: generateSlug('Example title 78') },
    { title: 'Example title 79', duration: '4 mins', tag: 'SEO', slug: generateSlug('Example title 79') },
    { title: 'Example title 80', duration: '1 min', tag: 'Sales', slug: generateSlug('Example title 80') },
    { title: 'Example title 81', duration: '3 mins', tag: 'Social', slug: generateSlug('Example title 81') },
    { title: 'Example title 82', duration: '2 mins', tag: 'Ads', slug: generateSlug('Example title 82') },
    { title: 'Example title 83', duration: '5 mins', tag: 'Copywriting', slug: generateSlug('Example title 83') },
    { title: 'Example title 84', duration: '4 mins', tag: 'Landing Page', slug: generateSlug('Example title 84') },
    { title: 'Example title 85', duration: '1 min', tag: 'Retention', slug: generateSlug('Example title 85') }
];
